<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Creates the warnings table — compliance escalation records.
     * Three levels of warnings:
     *   level_1: Dashboard notification to participant
     *   level_2: Email notification to assigned admin
     *   level_3: Broad alert / formal escalation
     *
     * Warnings are auto-generated by the scheduler when quota
     * is not met within the attendance period.
     */
    public function up(): void
    {
        Schema::create('warnings', function (Blueprint $table) {
            $table->id();

            // Link to participant — cascade delete
            $table->foreignId('participant_id')->constrained('participants')->onDelete('cascade');

            // Link to the attendance period that triggered this warning
            $table->unsignedBigInteger('attendance_period_id')->nullable();
            $table->foreign('attendance_period_id')
                  ->references('id')
                  ->on('attendance_periods')
                  ->onDelete('set null');

            // Warning severity level
            $table->string('level', 10);  // 'level_1', 'level_2', 'level_3'

            // Human-readable explanation of why warning was issued
            $table->text('reason');

            // When the warning was issued
            $table->timestamp('issued_at');

            // Warning lifecycle status
            $table->string('status', 20)->default('active');

            // When the warning was resolved/acknowledged
            $table->timestamp('resolved_at')->nullable();

            // Admin notes on resolution
            $table->text('notes')->nullable();

            // Which admin or system issued this warning
            $table->unsignedBigInteger('created_by')->nullable();
            $table->foreign('created_by')
                  ->references('id')
                  ->on('users')
                  ->onDelete('set null');

            $table->timestamps();

            // Prevent duplicate same-level warnings in the same period
            $table->unique(
                ['participant_id', 'attendance_period_id', 'level'],
                'warnings_unique_level_per_period'
            );
        });

        // Add PostgreSQL CHECK constraint for warning level values
        DB::statement("ALTER TABLE warnings ADD CONSTRAINT warnings_level_check CHECK (level IN ('level_1', 'level_2', 'level_3'))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('warnings');
    }
};
